### ISSUE TITLE
Change txt for input questions

### ISSUE THREAD

**Issue by randalljam** [lemdt/CovidShinyModel#35]
Number of Days from Infection to Becoming Infectious (Latent Period)
Percent of Infected that are Hospitalized
For Hospitalized, Number of Days from Infection to Hospitalization (Infectious Period Hosp)
For Non-Hospitalized, Number of Days from Infection to No Longer Infectious (Infectious Period Non-Hosp)

The inputs below are transition probabilities, meaning the chance on a daily basis for an infected patient to move from one state to another.  These % are not long term odds.
For General Inpatients (Non-ICU), what is the probability that tomorrow:
General Inpatient goes to the ICU?
General Inpatient is Discharged?

For ICU Patients not on a Ventilator, what is the probability that tomorrow:
ICU Patient Returns To Being a General Inpatient?
ICU Patient Goes on a Ventilator?

For Ventilated Patients, what is the probability that tomorrow:
Move off the Ventilator?
Die?

** All Ventilated Patients must first go through the ICU
For the Internal Hospital Model, the "ICU" state comprises Non-Ventilated ICU Patients, and the "G" state excludes all ICU and Ventilated Patients
For Reporting, all 3 states "G" (Inpatients), "ICU" (Non-Ventialted ICU Patients) and "V" (Ventilated) are considered "Hospitalized", i.e. Inside the Hospital.
For Reporting, "V" (Ventilated Patients) are considered to be in the ICU.

**Comment by jpspeng** [comment]
this is done
