### ISSUE TITLE
should not be able to set duration of incubation to 0 as it crashed thing. should be min 1.

### ISSUE THREAD

**Issue by randalljam** [lemdt/CovidShinyModel#53]

**Comment by randalljam** [comment]
Did you take care of this one James? I recall seeing something about that but can't find it amongst our many platforms.

**Comment by jpspeng** [comment]
@randalljam this is done but I haven't pushed the changes to the website yet. Also let's keep this open so that we don't forget to do this in the refactored code.

**Comment by jpspeng** [comment]
This is done and merged into master
