### ISSUE TITLE
Have the ability to ‘freeze’ a projection

### ISSUE THREAD

**Issue by jpspeng** [lemdt/CovidShinyModel#59]
1) If only one plot is selected on the graph, then a textInput, an action button that says “Freeze,” and an action button that says “Reset” should appear.  
![image](https://user-images.githubusercontent.com/18298913/78331552-260b0c80-753b-11ea-9421-38f22cfcc81a.png)

2) When ‘Freeze’ is pressed, then the current plot is ‘frozen’ on the graph, and the variable name changes from (in this case)  ‘Active’  to ‘[Text]’ in the legend.

3) Then when the user selects another set of parameters for a projection, the line from the first projection stays the same, but the new projection appears on the graph overlayed on the original. 

4) You can freeze an unlimited number of times, each with a different color. 

5) When you press reset, then all of the ‘frozen’ lines disappear. 

6) You can’t select more than one checkbox if there are any frozen lines. This is so the graph doesn’t get too busy.

**Comment by randalljam** [comment]
Great, this is a nice implementation. One tweak, instead of "Reset" let's use "Clear"
