### ISSUE TITLE
coding error in new.influx

### ISSUE THREAD

**Issue by LauraBalzer** [lemdt/CovidShinyModel#61]
Hi, 
If we are allowing for influxes to the population, then we need the population size N also needs to be a vector of length num.days, which is updated to include these folks. Something like the following.
Thanks,
Laura

    if (influx[['day']] == tt - 1) {
      S[tt] <- S[tt] - influx[['num.influx']]
      E[tt] <- E[tt] + influx[['num.influx']]
      N[tt] <- N[tt] + influx[['num.influx']]
    }

**Comment by jpspeng** [comment]
Yeah, right now it assumes an "influx" means that on a specific day, a bunch of susceptible people included originally in the population instantaneously become exposed. (So the population size is not changed.)

I thought of this in terms of say, SF residents on vacation in Italy all return home on March 16th. I realize that current coding doesn't capture this situation perfectly, but neither (I don't think) does adding people to the original population. 

Anyway, just explaining what I was thinking. I think to your point, the word 'influx' also sort of implies in-migration.

**Comment by LauraBalzer** [comment]
great. thanks for the explanation. i think downstream it would be good to code as a mix of exposed and infectious (e.g. to account for springbreakers who are returning after Mar16 and are currently infectious). agree that not priority issue.
