### ISSUE TITLE
more ppl in ICU/vent than hosp at day0

### ISSUE THREAD

**Issue by LauraBalzer** [lemdt/CovidShinyModel#62]
Hi, 
I think there is an issue with days.shift==0 projections. See screenshot below. There are more people in the ICU and on ventilators than in the hospital. In the server.R, I think we need something like the following. But this is very hack-y.... And may not give a good alignment for projections at days.shift>0
Thanks,
Laura

seir.df[seir.df$days.shift == 0, ]$icu <- input$num_hospitalized*icu.rate
seir.df[seir.df$days.shift == 0, ]$vent <- input$num_hospitalized*icu.rate*vent.rate

![Screen Shot 2020-04-03 at 8 42 39 AM](https://user-images.githubusercontent.com/25786178/78361929-3052f800-7587-11ea-9e55-2004bfb84989.png)

**Comment by jpspeng** [comment]
Good catch, @LauraBalzer what are the set of inputs that produce this? Thanks

**Comment by randalljam** [comment]
Sounds like a date alignment bug. We have to fix this for interventions in the past, which is the top priority Fri am. But it's important to understand that we are not using "day0" terminology as previously, and this is connected to date alignment. We are now modeling the entire SEIR curve, and day0 is the day of the 1st person in E. Day0 is not a user facing parameter anymore, only calendar dates are facing.

**Comment by LauraBalzer** [comment]
@randalljam: Yes; understood. It's an issue with user input as inputed calendar date (i.e. code dayshift==0). See line 705 in server.R, there is a hack to replace the SEIR projected # hospitalizations with the inputted one. We cannot just replace the # hospitalizations without also tweaking the # in ICU and # ventilated - as I suggested above

**Comment by LauraBalzer** [comment]
also noting day0 is still in the user output as shown in above screenshot... but i do think this use of day0 is clear.

**Comment by LauraBalzer** [comment]
@jpspeng - i was able to recreate. there something funky going on if you click between input metric as hospitalizations vs. cases. 
1) input as hospitalizations with 20 hospitalized on 3/16 ... output 3/16 (day0) with 20 in hosp, 10 in ICU, 9 in vent. 
2) click on input as cases
3) click back on input as hospitalizations. update estimated num hospitalized back to 20... output 3/16 (day0) with 20 in hosp, 25 in ICU, 25 in vent.

**Comment by jpspeng** [comment]
Ah yeah. Thanks. That is a bug.

**Comment by jpspeng** [comment]
@LauraBalzer this is fixed in the original code but I'm going to keep this issue open so that we remember to change this in the refactored code. 

Here are the changes for your reference: 
https://github.com/jpspeng/CovidShinyModel/pull/1/files

**Comment by randalljam** [comment]
This is connected to the issue of whether to replace the Hosp curve data with the user input hospitalization on the specific date. I'll create a separate issue for that.
